obstaclesDistanceInfluence_m: 0.3
max_vel_x: 0.75
max_vel_theta: 1.0
force_scale: 0.25
momentum_scale: 0.1
rate: 10
minScanRange: 0.2
maxScanRange: 6.0

gbnEnabled: false
GUI: false

# to enable gbn use rosparam set gbnEnabled true

