base_frame_id: base_frame
laser_topic: scan
map_topic: map
static_map_service: map
max_linear_vel: 0.75
max_angular_vel: 1.0
min_angular_vel: 0.1
max_linear_acc: 0.3
max_angular_acc: 0.5
robot_radius: 0.2
goal_translation_tolerance: 0.3
goal_rotation_tolerance: 0.2
tf_timecheck: false

use_gui: false
verbose: false

