pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_speed: 0.20
    motor:
        id: 2
        init: 512
        min: 316
        max: 708

tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 0.20
    motor:
        id: 1
        init: 512
        min: 316
        max: 708

        
spallasx_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: spallasx_joint
    joint_speed: 1
    motor:
        id: 6
        init: 0
        min: 0
        max: 1023
        
spallasxj_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: spallasxj_joint
    joint_speed: 1
    motor:
        id: 7
        init: 0
        min: 0
        max: 1023
        
spalladx_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: spalladx_joint
    joint_speed: 1
    motor:
        id: 3
        init: 0
        min: 0
        max: 1023        
        
spalladxj_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: spallasxj_joint
    joint_speed: 1
    motor:
        id: 4
        init: 0
        min: 0
        max: 1023
        
        
gomitodx_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: gomitodx_joint
    joint_speed: 1
    motor:
        id: 5
        init: 0
        min: 0
        max: 1023        
        
gomitosx_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: gomitosx_joint
    joint_speed: 1
    motor:
        id: 8
        init: 0
        min: 0
        max: 1023
